name = "Presentation"
license = "MIT"
licenselink = ""
description = ""
homepage = ""
tags = []
features = []
min_version = "0.41"

[author]
  name = "Florian Weingartshofer"
  homepage = "flwr.dev"

